#!/usr/bin/env bash


#---------------------
# Aquire IDs
#---------------------


#----- IMPI
# Downloaded latest version as IMPI 2021 version (IMPI-2021-Q4pre) xlsx file from:
# https://www.mrc-mbu.cam.ac.uk/research-resources-and-facilities/impi
# Saved only ENSEMBL column as impi-2021-q4pre-20211001-dist_0.ids


#----- MitoCarta3.0
# Downloaded latest version as Human.MitoCarta3.0.xls file from:
# https://www.broadinstitute.org/mitocarta/mitocarta30-inventory-mammalian-mitochondrial-proteins-and-pathways
# Saved only EnsemblGeneID_mapping_version_20200130 column from A Human MitoCarta3.0 sheet as csv file
# Some lines contained multiple IDs separated by |
# I splitted them using:
cat ./Data/Mitochondrial_catalogues/Human.MitoCarta3.0.csv | sed -z 's/|/\n/g' > ./Data/Mitochondrial_catalogues/Human.MitoCarta3.0.ids


#----- IMPI and MitoCarta3.0
# ID files from both catalogues where concatenated, duplicates were removed using:
cat ./Data/Mitochondrial_catalogues/impi-2021-q4pre-20211001-dist_0.ids ./Data/Mitochondrial_catalogues/Human.MitoCarta3.0.ids | sort | uniq > ./Data/Mitochondrial_catalogues/impi_and_MitoCarta.ids


#---------------------
# Prepare gencode.v45.annotation slices
#---------------------

#----- Gencode.v45.annotation
# Comprehensive gene annotation gtf file was downloaded from https://www.gencodegenes.org/human/

for id_file in ./Data/Mitochondrial_catalogues/*ids
    do
        filename=$(basename -- "$id_file")
        extension="${filename##*.}"
        filename="${filename%.*}"
        echo $filename
        zcat ./Data/Mitochondrial_catalogues/gencode.v45.annotation.gtf.gz | grep -f $id_file > ./Data/Processed/Mitochondrial/${filename}.gencode.v45.annotation_slice.gtf
        cat ./Data/Processed/Mitochondrial/$filename.gencode.v45.annotation_slice.gtf | awk '{print $10}' | sed 's/"//g ; s/;//g'| awk -F'.' '{print $1}' | sort | uniq | grep -vf - $id_file > ./Data/Processed/Mitochondrial/${filename}.gencode.v45.annotation_slice.missing.ids
    done;


#---------------------
# Prepare masterTable slices
#---------------------

#----- masterTable annotation
# Hv3_enhancedCLS3_refined_+gencodev43.loci.refmerged gtf file was downloaded from https://github.com/guigolab/gencode-cls-master-table/releases


for id_file in ./Data/Mitochondrial_catalogues/*ids
    do
        filename=$(basename -- "$id_file")
        extension="${filename##*.}"
        filename="${filename%.*}"
        zcat ./Data/masterTable/Hv3_enhancedCLS3_refined_+gencodev43.loci.refmerged.gff.gz | grep -f $id_file > ./Data/Processed/Mitochondrial/${filename}_mT_Hv3_enhancedCLS3_slice.gtf
        cat ./Data/Processed/Mitochondrial/${filename}_mT_Hv3_enhancedCLS3_slice.gtf | awk '{print $10}' | sed 's/"//g ; s/;//g'| awk -F'.' '{print $1}' | sort | uniq | grep -vf - $id_file > ./Data/Processed/Mitochondrial/${filename}_mT_Hv3_enhancedCLS3_slice.missing.ids
    done;


#---------------------
# Calculate stats for Gencode.v45.annotation and masterTable annotation slices
#---------------------

printf 'Stats calculated for Gencode.v45 and mT_Hv3 slices\n' > ./Data/Processed/Mitochondrial/mito_stats # Remove file content
for annotation_slice in ./Data/Processed/Mitochondrial/*.gtf
    do
        filename=$(basename -- "$annotation_slice")
        extension="${filename##*.}"
        filename="${filename%.*}"
        echo $filename
        missing_gene_ids=$(cat ./Data/Processed/Mitochondrial/${filename}.missing.ids | sort | uniq | wc -l)
        slice_gene_ids=$(cat $annotation_slice | awk '{print $10}' | sort | uniq | wc -l)
        transcript_ids=$(cat $annotation_slice | awk '$3=="transcript"' | awk '{print $12}' | sort | uniq | wc -l)

        printf '%s:\n' "$filename" >> ./Data/Processed/Mitochondrial/mito_stats
        printf 'Missing gene_ids: %s\n' "$missing_gene_ids" >> ./Data/Processed/Mitochondrial/mito_stats
        printf 'Common gene_ids: %s\n' "$slice_gene_ids" >> ./Data/Processed/Mitochondrial/mito_stats
        printf 'Commontranscript_ids: %s\n' "$transcript_ids" >> ./Data/Processed/Mitochondrial/mito_stats
        printf '%s\n' "-----------------------" >> ./Data/Processed/Mitochondrial/mito_stats
    done

# "ENST00000482405.7_PAR_Y"; <- id sztucznie zwiększające liczbę genów

# sed "s/_PAR_Y//g"   
#  awk '$1 !~ /_PAR_Y/' | awk -F'.' '{print$1}' |

# echo $filename
#         gene_ids=$(cat $annotation_slice | awk '$3=="transcript"' | awk '{print $10}' | sort | uniq | wc -l)
#         missing_gene_ids=$(cat ${filename}.missing.ids | awk '$3=="transcript"' | awk '{print $10}' | sort | uniq | wc -l)
#         transcript_ids=$(cat $annotation_slice | awk '$3=="transcript"' | awk '{print $12}' | sort | uniq | wc -l)




