---
title: "R Notebook"
output: html_notebook
---

# Load Libraries
```{r}
library(dplyr)
library(ggplot2)
library(ggVennDiagram)
```


# Load data
```{r}
df_mito <- read.delim("../Data/Mitochondrial_catalogues/Human.MitoCarta3.0.ids",
                      sep="\t",
                      header = FALSE)
colnames(df_mito) <- c("gene_id")


df_impi <- read.delim("../Data/Mitochondrial_catalogues/impi-2021-q4pre-20211001-dist_0.ids",
                      sep="\t",
                      header = FALSE)
colnames(df_impi) <- c("gene_id")

df_mito_impi <- df_mito %>%
  bind_rows(df_impi) %>%
  distinct()


df_gencode45 <- read.delim("../Data/Gencode_annotations/gencode.v45.annotation.ids",
                         sep="\t",
                         header = FALSE)
colnames(df_gencode45) <- c("gene_id",
                          "transcript_id")


df_gencode44 <- read.delim("../Data/Gencode_annotations/gencode.v44.annotation.ids",
                         sep="\t",
                         header = FALSE)
colnames(df_gencode44) <- c("gene_id",
                          "transcript_id")


df_gencode27 <- read.delim("../Data/Gencode_annotations/gencode.v27.annotation.ids",
                         sep="\t",
                         header = FALSE)
colnames(df_gencode27) <- c("gene_id",
                          "transcript_id")


df_mT <- read.delim("../Data/masterTable/Hv3_enhancedCLS3_refined_+gencodev43.loci.refmerged.ids",
                    sep="\t",
                    header = FALSE)
colnames(df_mT) <- c("gene_id",
                     "transcript_id")

df_mT_mitoImpi_slice <- read.delim("../Data/Processed/Mitochondrial/impi_and_MitoCarta_mT_Hv3_enhancedCLS3_slice.ids",
                                   sep="\t",
                                   header = FALSE)
colnames(df_mT_mitoImpi_slice) <- c("gene_id",
                                    "transcript_id")


df_gencode45_mitoImpi_slice <- read.delim("../Data/Processed/Mitochondrial/impi_and_MitoCarta.gencode.v45.annotation.gtf_slice.ids",
                                        sep="\t",
                                        header = FALSE)
colnames(df_gencode45_mitoImpi_slice) <- c("gene_id",
                                         "transcript_id")

df_gencode44_mitoImpi_slice <- read.delim("../Data/Processed/Mitochondrial/impi_and_MitoCarta.gencode.v44.annotation.gtf_slice.ids",
                                        sep="\t",
                                        header = FALSE)
colnames(df_gencode44_mitoImpi_slice) <- c("gene_id",
                                         "transcript_id")


df_gencode27_mitoImpi_slice <- read.delim("../Data/Processed/Mitochondrial/impi_and_MitoCarta.gencode.v27.annotation.gtf_slice.ids",
                                        sep="\t",
                                        header = FALSE)
colnames(df_gencode27_mitoImpi_slice) <- c("gene_id",
                                         "transcript_id")

```
"Human.MitoCarta3.0",
"impi-2021-q4pre-20211001-dist_0",
"gencode.v45.annotation",
"Hv3_enhancedCLS3_refined_+gencodev43.loci.refmerged"

# Venn diagram
```{r}
venn_all_45 <- ggVennDiagram(list(Gencode45 = df_gencode45$gene_id,
                               Mitocarta = df_mito$gene_id,
                               Impi = df_impi$gene_id,
                          masterTable = df_mT$gene_id),
                          label_alpha = 0) +
  scale_fill_gradient(low = "#c0ddf0", high = "#4981BF") +
  scale_x_continuous(expand = expansion(mult = .2)) +
  theme(legend.position = "none")

venn_all_44 <- ggVennDiagram(list(Gencode44 = df_gencode44$gene_id,
                               Mitocarta = df_mito$gene_id,
                               Impi = df_impi$gene_id,
                          masterTable = df_mT$gene_id),
                          label_alpha = 0) +
  scale_fill_gradient(low = "#c0ddf0", high = "#4981BF") +
  scale_x_continuous(expand = expansion(mult = .2)) +
  theme(legend.position = "none")

venn_all_27 <- ggVennDiagram(list(Gencode27 = df_gencode27$gene_id,
                               Mitocarta = df_mito$gene_id,
                               Impi = df_impi$gene_id,
                          masterTable = df_mT$gene_id),
                          label_alpha = 0) +
  scale_fill_gradient(low = "#c0ddf0", high = "#4981BF") +
  scale_x_continuous(expand = expansion(mult = .2)) +
  theme(legend.position = "none")

venn_gencode45 <- ggVennDiagram(list(Mitocarta = df_mito$gene_id,
                                   Gencode45 = df_gencode45$gene_id,
                                   Impi = df_impi$gene_id),
                              label_alpha = 0) +
  scale_fill_gradient(low = "#F4FAFE", high = "#4981BF", trans = "log") +
  scale_x_continuous(expand = expansion(mult = .2)) +
  theme(legend.position = "none")

venn_gencode44 <- ggVennDiagram(list(Mitocarta = df_mito$gene_id,
                                   Gencode44 = df_gencode44$gene_id,
                                   Impi = df_impi$gene_id),
                              label_alpha = 0) +
  scale_fill_gradient(low = "#F4FAFE", high = "#4981BF", trans = "log") +
  scale_x_continuous(expand = expansion(mult = .2)) +
  theme(legend.position = "none")

venn_gencode27 <- ggVennDiagram(list(Mitocarta = df_mito$gene_id,
                                   Gencode27 = df_gencode27$gene_id,
                                   Impi = df_impi$gene_id),
                              label_alpha = 0) +
  scale_fill_gradient(low = "#F4FAFE", high = "#4981BF", trans = "log") +
  scale_x_continuous(expand = expansion(mult = .2)) +
  theme(legend.position = "none")

venn_mT <- ggVennDiagram(list(Mitocarta = df_mito$gene_id,
                              masterTable = df_mT$gene_id,
                              Impi = df_impi$gene_id),
                         label_alpha = 0) +
  scale_fill_gradient(low = "#F4FAFE", high = "#4981BF", trans = "log") +
  scale_x_continuous(expand = expansion(mult = .2)) +
  theme(legend.position = "none")

venn_mitoImpi_gencode45 <- ggVennDiagram(list(Mitocarta_impi = df_mito_impi$gene_id,
                                             Gencode45 = df_gencode45$gene_id),
                                        label_alpha = 0) +
  scale_fill_gradient(low = "#F4FAFE", high = "#4981BF", trans = "log") +
  scale_x_continuous(expand = expansion(mult = .2)) +
  theme(legend.position = "none")

venn_mitoImpi_gencode44 <- ggVennDiagram(list(Mitocarta_impi = df_mito_impi$gene_id,
                                             Gencode44 = df_gencode44$gene_id),
                                        label_alpha = 0) +
  scale_fill_gradient(low = "#F4FAFE", high = "#4981BF", trans = "log") +
  scale_x_continuous(expand = expansion(mult = .2)) +
  theme(legend.position = "none")

venn_mitoImpi_gencode27 <- ggVennDiagram(list(Mitocarta_impi = df_mito_impi$gene_id,
                                             Gencode27 = df_gencode27$gene_id),
                                        label_alpha = 0) +
  scale_fill_gradient(low = "#F4FAFE", high = "#4981BF", trans = "log") +
  scale_x_continuous(expand = expansion(mult = .2)) +
  theme(legend.position = "none")

venn_mitoImpi_mt <- ggVennDiagram(list(Mitocarta_impi = df_mito_impi$gene_id,
                                        masterTable = df_mT$gene_id),
                                   label_alpha = 0) +
  scale_fill_gradient(low = "#F4FAFE", high = "#4981BF", trans = "log") +
  scale_x_continuous(expand = expansion(mult = .2)) +
  theme(legend.position = "none")


venn_mito_impi <- ggVennDiagram(list(Mitocarta = df_mito$gene_id,
                                     Impi = df_impi$gene_id),
                                        label_alpha = 0) +
  scale_fill_gradient(low = "#F4FAFE", high = "#4981BF", trans = "log") +
  scale_x_continuous(expand = expansion(mult = .2)) +
  theme(legend.position = "none")


venn_gencode45_mitoImpi_slice <- ggVennDiagram(list(Mitocarta = df_mito$gene_id,
                                                  "Gencode45 slice" = df_gencode45_mitoImpi_slice$gene_id,
                                                  Impi = df_impi$gene_id),
                                        label_alpha = 0) +
  scale_fill_gradient(low = "#F4FAFE", high = "#4981BF") +
  scale_x_continuous(expand = expansion(mult = .2)) +
  theme(legend.position = "none")


venn_gencode44_mitoImpi_slice <- ggVennDiagram(list(Mitocarta = df_mito$gene_id,
                                                  "Gencode44 slice" = df_gencode44_mitoImpi_slice$gene_id,
                                                  Impi = df_impi$gene_id),
                                        label_alpha = 0) +
  scale_fill_gradient(low = "#F4FAFE", high = "#4981BF") +
  scale_x_continuous(expand = expansion(mult = .2)) +
  theme(legend.position = "none")


venn_gencode27_mitoImpi_slice <- ggVennDiagram(list(Mitocarta = df_mito$gene_id,
                                                  "Gencode27 slice" = df_gencode27_mitoImpi_slice$gene_id,
                                                  Impi = df_impi$gene_id),
                                        label_alpha = 0) +
  scale_fill_gradient(low = "#F4FAFE", high = "#4981BF") +
  scale_x_continuous(expand = expansion(mult = .2)) +
  theme(legend.position = "none")


venn_mT_mitoImpi_slice <- ggVennDiagram(list(Mitocarta = df_mito$gene_id,
                                             "masterTable slice" = df_mT_mitoImpi_slice$gene_id,
                                             Impi = df_impi$gene_id),
                                        label_alpha = 0) +
  scale_fill_gradient(low = "#F4FAFE", high = "#4981BF") +
  scale_x_continuous(expand = expansion(mult = .2)) +
  theme(legend.position = "none")


#pdf(file = "../Plots/mitochondrial_gene_id_venn.pdf", width = 6, height = 4)
venn_all_45
venn_all_44
venn_all_27
venn_gencode45
venn_gencode44
venn_gencode27
venn_mT
venn_mitoImpi_gencode45
venn_mitoImpi_gencode44
venn_mitoImpi_gencode27
venn_mitoImpi_mt
venn_mito_impi
venn_gencode45_mitoImpi_slice
venn_gencode44_mitoImpi_slice
venn_gencode27_mitoImpi_slice
venn_mT_mitoImpi_slice
#dev.off()
```

# Barplots
```{r}
# Prepare data
df_only_mito <-
  left_join(x=df_mito, y=df_impi, by="gene_id", keep=TRUE) %>% 
  filter(is.na(gene_id.y)) %>%
  select(gene_id.x) %>% 
  rename(gene_id = gene_id.x) %>% 
  mutate(catalogue="mitocarta")
  
df_only_impi <-
  left_join(x=df_impi, y=df_mito, by="gene_id", keep=TRUE) %>% 
  filter(is.na(gene_id.y)) %>%
  select(gene_id.x) %>% 
  rename(gene_id = gene_id.x) %>% 
  mutate(catalogue="impi")

df_mito_impi_intersect <-
  inner_join(x=df_impi, y=df_mito, by="gene_id") %>% 
  mutate(catalogue="impi+mitocarta")

df_gencode45_slice_composition <-
  left_join(x=df_gencode45_mitoImpi_slice, y=(bind_rows(df_only_mito, df_only_impi, df_mito_impi_intersect)), by="gene_id") %>% 
  replace(is.na(.),"other") %>% 
  mutate(data_source = "Gencode.v45")


df_gencode44_slice_composition <-
  left_join(x=df_gencode44_mitoImpi_slice, y=(bind_rows(df_only_mito, df_only_impi, df_mito_impi_intersect)), by="gene_id") %>% 
  replace(is.na(.),"other") %>% 
  mutate(data_source = "Gencode.v44")


df_gencode27_slice_composition <-
  left_join(x=df_gencode27_mitoImpi_slice, y=(bind_rows(df_only_mito, df_only_impi, df_mito_impi_intersect)), by="gene_id") %>% 
  replace(is.na(.),"other") %>% 
  mutate(data_source = "Gencode.v27")

  
df_mT_slice_composition <-
  left_join(x=df_mT_mitoImpi_slice, y=(bind_rows(df_only_mito, df_only_impi, df_mito_impi_intersect)), by="gene_id") %>% 
  replace(is.na(.),"other") %>% 
  mutate(data_source = "masterTable")

# Stacked bar plot for gencode and masterTable
bind_rows(df_gencode45_slice_composition, df_gencode44_slice_composition, df_gencode27_slice_composition, df_mT_slice_composition) %>% 
  group_by(data_source, catalogue) %>% 
  summarise(number_of_transcripts = n()) %>% 
  mutate(percent = prop.table(number_of_transcripts)) %>% 
  # Plot data using barplot
  ggplot(data=.,
         aes(x=data_source,#reorder(technology, -percent),
             y=percent,
             fill=factor(catalogue, levels=c("mitocarta", "impi", "impi+mitocarta")))) + 
  geom_bar(stat="identity") +
  geom_text(aes(label = paste0(catalogue, " (", scales::comma(number_of_transcripts), ")")),
            position=position_stack(vjust=0.5),
            size = 3) +
  theme_minimal() +
  scale_fill_manual(values=c("#d386b7", "#6fb293", "#728fb4")) +  # "#93ae55", "#d70e17", "#1887ab", "#a9629f"
  ylab('Percentage of transcript ids') +
  xlab('Data source') +
  theme(legend.position = "none",
        axis.ticks.y = element_line(colour = "black"),
        plot.title = element_text(hjust = 0.5,
                                  size=11.0),
        panel.background = element_rect(fill = NA),
        panel.grid.major.x = element_line(colour = NA),
        panel.grid.minor.x = element_line(colour = NA),
        axis.text.y = element_text(colour="black",
                                  face="bold")) +
  ggtitle(label="Number of Gencode and masterTable transcripts common with MitoCarta, Impi or both databases") +
  scale_y_continuous(labels = scales::percent_format(),
                     limits = c(0,1)) -> bar_plot_gen_mT_slice_composition
  


#pdf(file = "../Plots/mitochondrial_transcripts_composition_barplot.pdf", width = 8, height = 5)
bar_plot_gen_mT_slice_composition
```

# Better plot to compare Gencode.v27 and masterTable slice

```{r}
# prepare data
data <- data.frame(Source = c("Gencode.v27", "Gencode.v27", "Gencode.v27", "masterTable", "masterTable", "masterTable",
                              "Gencode.v27", "Gencode.v27", "Gencode.v27", "masterTable", "masterTable", "masterTable"),
                   Catalog = c("mitocarta", "impi+mitocarta", "impi", "mitocarta", "impi+mitocarta", "impi",
                               "mitocarta", "impi+mitocarta", "impi", "mitocarta", "impi+mitocarta", "impi"),
                   Type = c("Genes", "Genes", "Genes", "Genes", "Genes", "Genes",
                            "Transcripts", "Transcripts", "Transcripts", "Transcripts", "Transcripts", "Transcripts"),
                   Count = c(140, 998, 358, 140, 997, 354,
                             1166, 8692, 3509, 1316, 10425, 4491)
                   )

data %>% 
  ggplot(aes(x=Source,
             y=Count,
             fill=factor(Catalog, levels=c("mitocarta", "impi+mitocarta", "impi")))) +
  geom_bar(stat="identity") +
  geom_text(aes(label=scales::comma(Count)),
            vjust=0.5,
            size=4, position=position_stack(vjust=0.5)) +
  theme_bw() +
  scale_fill_manual(values=c("#d386b7", "#6fb293", "#728fb4")) +
  ylab("Number of genes/transcripts") +
  theme(axis.text.y = element_text(size = 12,  colour = "black"),
        axis.text.x = element_text(size = 12,  colour = "black"),
        legend.text = element_text(size = 12),
        plot.title = element_text(size = 22, hjust = 0.5),
        legend.title = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size = 14),
        strip.text = element_text(size = 14)) +
  scale_y_continuous(label = scales::comma) +
  facet_wrap(~Type,
             scales = "free") -> comparison_plot
comparison_plot
```

# Save plot as pdf
```{r}
pdf(file = "../Plots/Mito_gen.v27-mT_comparison.pdf", width = 9, height = 5)
comparison_plot
```




















# JUNK
```{r}
# Stacked bar plot for mitoCarta and impi
df_only_gencode <-
  left_join(x=(df_gencode %>% 
                 select(gene_id) %>% 
                 distinct(gene_id)),
            y=(df_mT %>% 
                 select(gene_id) %>% 
                 distinct(gene_id)), by="gene_id", keep=TRUE) %>% 
  filter(is.na(gene_id.y)) %>%
  select(gene_id.x) %>% 
  rename(gene_id = gene_id.x) %>% 
  mutate(catalogue="gencode")
  
df_only_mT <-
  left_join(x=(df_mT %>%
                 select(gene_id) %>% 
                 distinct(gene_id)),
            y=(df_gencode %>% 
                 select(gene_id) %>% 
                 distinct(gene_id)), by="gene_id", keep=TRUE) %>% 
  filter(is.na(gene_id.y)) %>%
  select(gene_id.x) %>% 
  rename(gene_id = gene_id.x) %>% 
  mutate(catalogue="masterTable")

df_gencode_mt_intersect <-
  inner_join(x=(df_gencode %>% 
                  select(gene_id) %>% 
                  distinct(gene_id)),
             y=(df_mT %>% 
                  select(gene_id) %>% 
                  distinct(gene_id)), by="gene_id") %>% 
  mutate(catalogue="gencode+masterTable")

df_mito_composition <-
  left_join(x=df_mito, y=(bind_rows(df_only_gencode, df_only_mT, df_gencode_mt_intersect)), by="gene_id") %>% 
  replace(is.na(.),"other") %>% 
  mutate(data_source = "MitoCarta3.0")

df_impi_composition <-
  left_join(x=df_impi, y=(bind_rows(df_only_gencode, df_only_mT, df_gencode_mt_intersect)), by="gene_id") %>% 
  replace(is.na(.),"other") %>% 
  mutate(data_source = "IMPI-2021-Q4pre")

# Stacked bar plot for mitoCarta and impi
bind_rows(df_mito_composition, df_impi_composition) %>% 
  group_by(data_source, catalogue) %>% 
  summarise(number_of_genes = n()) %>% 
  mutate(percent = prop.table(number_of_genes)) %>% 
  # Plot data using barplot
  ggplot(data=.,
         aes(x=data_source,
             y=percent,
             fill=factor(catalogue, levels=c("other", "gencode", "gencode+masterTable", "masterTable")))) + 
  geom_bar(stat="identity") +
  geom_text(aes(label = paste0(catalogue, " (", scales::comma(number_of_genes), ")")),
            position=position_stack(vjust=0.5),
            size = 3.8) +
  theme_minimal() +
  scale_fill_manual(values=c("#ea8553", "#d386b7", "#6fb293", "#728fb4")) +  # "#93ae55", "#d70e17", "#1887ab", "#a9629f"
  ylab('Percentage of gene ids') +
  xlab('Data source') +
  theme(legend.position = "none",
        axis.ticks.y = element_line(colour = "black"),
        plot.title = element_text(hjust = 0.5,
                                  size=11.0),
        panel.background = element_rect(fill = NA),
        panel.grid.major.x = element_line(colour = NA),
        panel.grid.minor.x = element_line(colour = NA),
        axis.text.y = element_text(colour="black",
                                  face="bold")) +
  ggtitle(label="Number of MitoCarta and Impi genes common with gencode, masterTable or both annotations") +
  scale_y_continuous(labels = scales::percent_format(),
                     limits = c(0,1)) -> bar_plot_mito_impi_composition

bar_plot_mito_impi_composition
```

